services:
  - type: web
    name: terminalx-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
    healthCheckPath: /api/health
    autoDeploy: true
